#!/usr/bin/env bash
#
# A script to build FFmpeg so that it may be embedded in Screen. Special thanks to Darren Mo for providing a LGPL version 2.1 build script!
#
# Copyright (c) 2019 Darren Mo. Licensed under LGPL version 2.1.
#
# Modifications by Greg Cotten @ Video Village LLC
#
# TODO: Enable the following external libraries in order to
# support more formats/codecs/protocols.
#   AviSynth: libavxsynth
#   BluRay: libbluray
#   CELT: libcelt
#   codec2: libcodec2
#   DASH: libxml2
#   DVB teletext: libzvbi
#   Game Music Emu: libgme
#   Haivision SRT: libsrt
#   iLBC: libilbc
#   MOD: libopenmpt
#   SAMBA: libsmbclient
#   SFTP: libssh
#   Speex: libspeex
#   SVG: librsvg

SCRIPT_DIR="$(dirname "$BASH_SOURCE")"
cd "$SCRIPT_DIR"

# Use export MACOSX_DEPLOYMENT_TARGET=10.13 perhaps?

# Hack: We install the external libraries in a directory whose name
# does not contain spaces because the configure script does not
# properly handle spaces in the include/library paths returned by
# pkg-config.
EXTERNAL_LIBRARIES_DIR="$HOME/Library/co.videovillage.ScreenFFmpegBuild"
rm -rf "$EXTERNAL_LIBRARIES_DIR"
external-libraries/build-for-screen "$EXTERNAL_LIBRARIES_DIR" || exit $?

export DESTDIR="$SCRIPT_DIR/build"

cd ..

make clean
rm -rf "$DESTDIR"

export PKG_CONFIG_PATH="$EXTERNAL_LIBRARIES_DIR/lib/pkgconfig"
./configure \
   --prefix="/" \
   --extra-cflags='-mmacosx-version-min=10.13' \
   --extra-cxxflags='-mmacosx-version-min=10.13' \
   --extra-objcflags='-mmacosx-version-min=10.13' \
   --extra-ldflags='-mmacosx-version-min=10.13 -Z -L/usr/lib -F/System/Library/Frameworks' \
   --install-name-dir="@rpath/../Frameworks" \
   --disable-static \
   --enable-shared \
   --disable-programs \
   --disable-doc \
   --disable-postproc \
   --disable-w32threads \
   --disable-os2threads \
   --disable-amf \
   --disable-cuvid \
   --disable-d3d11va \
   --disable-dxva2 \
   --disable-ffnvcodec \
   --disable-nvdec \
   --disable-vaapi \
   --disable-vdpau \
   --enable-libdav1d \
   || exit $?

make install || exit $?

cd $SCRIPT_DIR

EXTERNAL_LIBS=$(basename "$EXTERNAL_LIBRARIES_DIR"/lib/*.dylib)
EXTERNAL_LIBS_NAMES=""

for LIB in $EXTERNAL_LIBS; do
    EXTERNAL_LIBS_NAMES+="${LIB%.*} "
done

cp "$EXTERNAL_LIBRARIES_DIR"/lib/*.dylib "$DESTDIR/lib/"
rm -rf "$EXTERNAL_LIBRARIES_DIR"

FFMPEG_LIBS="libavcodec libavdevice libavfilter libavformat libavutil libswresample libswscale"

mkdir "$DESTDIR/xcframeworks/"

for LIB in $FFMPEG_LIBS; do
  LIB_FRAMEWORK="$DESTDIR/xcframeworks/$LIB.framework"

  # build framework
  rm -rf $LIB_FRAMEWORK

  mkdir -p $LIB_FRAMEWORK/Headers
  cp -R $DESTDIR/include/$LIB/ $LIB_FRAMEWORK/Headers

  cp $DESTDIR/lib/$LIB.a $LIB_FRAMEWORK/$LIB

  cat > $LIB_FRAMEWORK/Info.plist << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$LIB</string>
	<key>CFBundleIdentifier</key>
	<string>org.ffmpeg.$LIB</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$LIB</string>
	<key>CFBundlePackageType</key>
	<string>FMWK</string>
	<key>CFBundleShortVersionString</key>
	<string>0.9</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>CFBundleSignature</key>
	<string>????</string>
</dict>
</plist>
EOF

  xcodebuild -create-xcframework -framework "$LIB_FRAMEWORK" -output "$DESTDIR/xcframeworks/$LIB.xcframework"

  rm -rf $LIB_FRAMEWORK
done

for LIB in $EXTERNAL_LIBS_NAMES; do
  xcodebuild -create-xcframework -library "$DESTDIR/lib/$LIB.dylib" -output "$DESTDIR/xcframeworks/$LIB.xcframework"
done

echo "build-for-screen completed successfully."